export const pets = [
  {
    id: "1",
    name: "Mochi",
    species: "Mèo",
    breed: "Mèo Anh lông ngắn",
    age: "2 tuổi",
    birthDate: "15/03/2024",
    weight: "4.5 kg",
    gender: "Cái",
    color: "Xám xanh",
    microchip: "VN-2024-001234",
    image: "/cute-british-shorthair-cat.jpg",
    personality: ["Hướng nội", "Thích ngủ", "Hay kén ăn"],
    allergies: ["Hải sản"],
    notes: "Cần kiểm tra răng định kỳ",
  },
  {
    id: "2",
    name: "Lucky",
    species: "Chó",
    breed: "Corgi",
    age: "3 tuổi",
    birthDate: "20/06/2023",
    weight: "12 kg",
    gender: "Đực",
    color: "Vàng trắng",
    microchip: "VN-2023-005678",
    image: "/adorable-corgi-dog-smiling.jpg",
    personality: ["Năng động", "Thân thiện", "Thích chạy nhảy"],
    allergies: [],
    notes: "Thích đi dạo buổi sáng",
  },
  {
    id: "3",
    name: "Bông",
    species: "Thỏ",
    breed: "Holland Lop",
    age: "1 tuổi",
    birthDate: "10/01/2025",
    weight: "2 kg",
    gender: "Cái",
    color: "Trắng",
    microchip: "VN-2025-009012",
    image: "/fluffy-white-holland-lop-rabbit.jpg",
    personality: ["Nhút nhát", "Thích cà rốt", "Hay ngủ ngày"],
    allergies: ["Cỏ khô"],
    notes: "Cần môi trường yên tĩnh",
  },
]

export const medicalRecords = [
  {
    id: "1",
    petId: "1",
    date: "15/12/2025",
    type: "Tiêm phòng",
    category: "vaccine",
    description: "Vaccine dại + 5 bệnh (FVRCP)",
    clinic: "PetCare Clinic",
    vet: "BS. Nguyễn Văn An",
    cost: 450000,
    nextAppointment: "15/12/2026",
    attachments: ["vaccine_certificate.pdf"],
    notes: "Phản ứng tốt, không có tác dụng phụ",
  },
  {
    id: "2",
    petId: "1",
    date: "20/11/2025",
    type: "Khám tổng quát",
    category: "checkup",
    description: "Khám sức khỏe định kỳ 6 tháng",
    clinic: "Happy Pet Hospital",
    vet: "BS. Trần Thị Bình",
    cost: 300000,
    nextAppointment: "20/05/2026",
    results: {
      weight: "4.5 kg",
      heartRate: "120 bpm",
      temperature: "38.5°C",
      bloodPressure: "120/80 mmHg",
    },
    notes: "Sức khỏe tốt, không có vấn đề",
  },
  {
    id: "3",
    petId: "1",
    date: "05/10/2025",
    type: "Tẩy giun",
    category: "treatment",
    description: "Tẩy giun định kỳ 3 tháng - Drontal Plus",
    clinic: "PetCare Clinic",
    vet: "BS. Nguyễn Văn An",
    cost: 150000,
    nextAppointment: "05/01/2026",
    notes: "Tẩy giun định kỳ 3 tháng",
  },
  {
    id: "4",
    petId: "1",
    date: "01/08/2025",
    type: "Phẫu thuật",
    category: "surgery",
    description: "Triệt sản (spay)",
    clinic: "Happy Pet Hospital",
    vet: "BS. Lê Văn Cường",
    cost: 1500000,
    notes: "Hồi phục tốt sau 2 tuần",
  },
  {
    id: "5",
    petId: "2",
    date: "10/12/2025",
    type: "Tiêm phòng",
    category: "vaccine",
    description: "Vaccine 7 bệnh chó + dại",
    clinic: "VetPro Center",
    vet: "BS. Phạm Thị Dung",
    cost: 500000,
    nextAppointment: "10/12/2026",
    notes: "Phản ứng bình thường",
  },
]

export const vaccineSchedule = [
  { id: "1", petId: "1", name: "FVRCP", dueDate: "15/12/2026", status: "upcoming" },
  { id: "2", petId: "1", name: "Dại", dueDate: "15/12/2026", status: "upcoming" },
  { id: "3", petId: "1", name: "Tẩy giun", dueDate: "05/01/2026", status: "due_soon" },
  { id: "4", petId: "2", name: "7 bệnh chó", dueDate: "10/12/2026", status: "upcoming" },
]

export const products = [
  {
    id: "1",
    name: "Royal Canin Indoor",
    category: "Thức ăn",
    price: 450000,
    rating: 4.8,
    image: "/premium-cat-food-bag.jpg",
    aiMatch: true,
    description: "Thức ăn hạt cho mèo trong nhà, ít muối",
    stock: 50,
    sold: 234,
  },
  {
    id: "2",
    name: "Pate Whiskas",
    category: "Thức ăn",
    price: 25000,
    rating: 4.5,
    image: "/cat-wet-food-can.jpg",
    aiMatch: true,
    description: "Pate mềm cho mèo, vị cá ngừ",
    stock: 100,
    sold: 567,
  },
  {
    id: "3",
    name: "Đồ chơi chuột",
    category: "Đồ chơi",
    price: 35000,
    rating: 4.2,
    image: "/cat-mouse-toy-colorful.jpg",
    aiMatch: false,
    description: "Chuột đồ chơi có chuông",
    stock: 80,
    sold: 123,
  },
  {
    id: "4",
    name: "Bàn cào móng",
    category: "Phụ kiện",
    price: 280000,
    rating: 4.7,
    image: "/cat-scratching-post.png",
    aiMatch: true,
    description: "Bàn cào móng kết hợp nhà nghỉ",
    stock: 25,
    sold: 89,
  },
]

export const services = [
  {
    id: "1",
    name: "Tắm Spa Cao Cấp",
    price: 250000,
    duration: "90 phút",
    rating: 4.9,
    reviews: 156,
    image: "/pet-spa-grooming.jpg",
    aiMatch: true,
    merchantId: "m1",
    merchantName: "PetCare Clinic",
    description: "Dịch vụ tắm spa cao cấp bao gồm tắm gội, sấy khô, cắt móng, vệ sinh tai và xịt thơm",
    category: "Spa & Grooming",
    availableTimes: ["09:00", "10:30", "14:00", "15:30", "17:00"],
    petTypes: ["Chó", "Mèo"],
  },
  {
    id: "2",
    name: "Cắt tỉa lông",
    price: 150000,
    duration: "60 phút",
    rating: 4.7,
    reviews: 89,
    image: "/pet-grooming-scissors.jpg",
    aiMatch: false,
    merchantId: "m1",
    merchantName: "PetCare Clinic",
    description: "Cắt tỉa lông theo yêu cầu, tạo kiểu đẹp cho bé cưng",
    category: "Spa & Grooming",
    availableTimes: ["09:00", "11:00", "14:00", "16:00"],
    petTypes: ["Chó", "Mèo"],
  },
  {
    id: "3",
    name: "Khám sức khỏe định kỳ",
    price: 200000,
    duration: "30 phút",
    rating: 4.8,
    reviews: 234,
    image: "/veterinary-checkup.jpg",
    aiMatch: true,
    merchantId: "m2",
    merchantName: "Happy Pet Hospital",
    description: "Khám tổng quát, kiểm tra sức khỏe toàn diện, tư vấn dinh dưỡng",
    category: "Y tế",
    availableTimes: ["08:00", "09:00", "10:00", "14:00", "15:00", "16:00"],
    petTypes: ["Chó", "Mèo", "Thỏ", "Hamster"],
  },
  {
    id: "4",
    name: "Tiêm phòng vaccine",
    price: 350000,
    duration: "20 phút",
    rating: 4.9,
    reviews: 312,
    image: "/pet-vaccination.jpg",
    aiMatch: true,
    merchantId: "m2",
    merchantName: "Happy Pet Hospital",
    description: "Tiêm phòng vaccine đầy đủ các loại bệnh, tư vấn lịch tiêm",
    category: "Y tế",
    availableTimes: ["08:30", "09:30", "10:30", "14:30", "15:30"],
    petTypes: ["Chó", "Mèo", "Thỏ"],
  },
  {
    id: "5",
    name: "Trông giữ thú cưng",
    price: 180000,
    duration: "Theo ngày",
    rating: 4.6,
    reviews: 78,
    image: "/pet-boarding.jpg",
    aiMatch: false,
    merchantId: "m3",
    merchantName: "PetStay Hotel",
    description: "Dịch vụ trông giữ thú cưng theo ngày/tuần, có camera giám sát 24/7",
    category: "Trông giữ",
    availableTimes: ["07:00", "08:00", "09:00"],
    petTypes: ["Chó", "Mèo"],
  },
]

export const merchantOrders = [
  {
    id: "ORD001",
    customer: "Nguyễn Văn A",
    customerPhone: "0901234567",
    product: "Royal Canin Indoor",
    quantity: 2,
    total: 900000,
    status: "pending",
    date: "10/01/2026",
    address: "123 Nguyễn Huệ, Q.1, TP.HCM",
  },
  {
    id: "ORD002",
    customer: "Trần Thị B",
    customerPhone: "0912345678",
    product: "Pate Whiskas x5",
    quantity: 5,
    total: 125000,
    status: "shipping",
    date: "09/01/2026",
    address: "456 Lê Lợi, Q.3, TP.HCM",
  },
  {
    id: "ORD003",
    customer: "Lê Văn C",
    customerPhone: "0923456789",
    product: "Đồ chơi chuột",
    quantity: 1,
    total: 35000,
    status: "done",
    date: "08/01/2026",
    address: "789 Điện Biên Phủ, Q.10, TP.HCM",
  },
  {
    id: "ORD004",
    customer: "Phạm Thị D",
    customerPhone: "0934567890",
    product: "Bàn cào móng",
    quantity: 1,
    total: 280000,
    status: "done",
    date: "07/01/2026",
    address: "321 Võ Văn Tần, Q.3, TP.HCM",
  },
]

export const merchantBookings = [
  {
    id: "BK001",
    customer: "Phạm Thị D",
    customerPhone: "0934567890",
    service: "Tắm Spa Cao Cấp",
    pet: "Mochi (Mèo Anh lông ngắn)",
    date: "12/01/2026",
    time: "10:00",
    status: "confirmed",
    notes: "Khách yêu cầu xịt thơm mùi hoa hồng",
  },
  {
    id: "BK002",
    customer: "Hoàng Văn E",
    customerPhone: "0945678901",
    service: "Cắt tỉa lông",
    pet: "Lucky (Corgi)",
    date: "12/01/2026",
    time: "14:00",
    status: "pending",
    notes: "",
  },
  {
    id: "BK003",
    customer: "Nguyễn Thị F",
    customerPhone: "0956789012",
    service: "Khám sức khỏe định kỳ",
    pet: "Bông (Thỏ Holland Lop)",
    date: "13/01/2026",
    time: "09:00",
    status: "confirmed",
    notes: "Thỏ hay ăn ít, cần kiểm tra",
  },
]

export const customerBookings = [
  {
    id: "BK001",
    serviceId: "1",
    serviceName: "Tắm Spa Cao Cấp",
    merchantName: "PetCare Clinic",
    petId: "1",
    petName: "Mochi",
    date: "12/01/2026",
    time: "10:00",
    status: "confirmed",
    price: 250000,
  },
  {
    id: "BK004",
    serviceId: "3",
    serviceName: "Khám sức khỏe định kỳ",
    merchantName: "Happy Pet Hospital",
    petId: "2",
    petName: "Lucky",
    date: "15/01/2026",
    time: "14:00",
    status: "pending",
    price: 200000,
  },
]

export const allUsers = [
  {
    id: "1",
    name: "Nguyễn Văn A",
    email: "nguyenvana@email.com",
    role: "customer",
    status: "active",
    createdAt: "01/01/2025",
    lastLogin: "10/01/2026",
    totalOrders: 15,
    totalSpent: 2500000,
  },
  {
    id: "2",
    name: "Trần Thị B",
    email: "tranthib@email.com",
    role: "customer",
    status: "active",
    createdAt: "15/02/2025",
    lastLogin: "09/01/2026",
    totalOrders: 8,
    totalSpent: 1200000,
  },
  {
    id: "3",
    name: "PetCare Clinic",
    email: "petcare@clinic.com",
    role: "merchant",
    status: "active",
    createdAt: "01/03/2025",
    lastLogin: "11/01/2026",
    totalOrders: 156,
    totalRevenue: 45000000,
  },
  {
    id: "4",
    name: "Happy Pet Shop",
    email: "happypet@shop.com",
    role: "merchant",
    status: "pending",
    createdAt: "20/12/2025",
    lastLogin: "-",
    totalOrders: 0,
    totalRevenue: 0,
  },
  {
    id: "5",
    name: "Admin Hệ thống",
    email: "admin@tailmates.com",
    role: "admin",
    status: "active",
    createdAt: "01/01/2024",
    lastLogin: "11/01/2026",
    totalOrders: 0,
    totalSpent: 0,
  },
]

export const subscriptionPackages = [
  {
    id: "1",
    name: "Gói Free",
    type: "customer",
    price: 0,
    features: ["Quản lý 1 thú cưng", "Xem sản phẩm", "Đặt dịch vụ cơ bản"],
    subscribers: 1250,
  },
  {
    id: "2",
    name: "Gói Thành Viên",
    type: "customer",
    price: 99000,
    features: [
      "Quản lý không giới hạn thú cưng",
      "Nút Diệu Kỳ AI",
      "Lưu trữ Full HD",
      "AI Tư vấn 24/7",
      "Ưu đãi độc quyền",
    ],
    subscribers: 456,
  },
  {
    id: "3",
    name: "Gói Đối Tác",
    type: "merchant",
    price: 299000,
    features: ["Đăng sản phẩm không giới hạn", "Quét QR Y tế", "Analytics nâng cao", "Hỗ trợ ưu tiên"],
    subscribers: 48,
  },
]

export const merchantServices = [
  {
    id: "1",
    name: "Tắm Spa Cao Cấp",
    price: 250000,
    duration: "90 phút",
    category: "Spa & Grooming",
    status: "active",
    bookings: 156,
    rating: 4.9,
  },
  {
    id: "2",
    name: "Cắt tỉa lông",
    price: 150000,
    duration: "60 phút",
    category: "Spa & Grooming",
    status: "active",
    bookings: 89,
    rating: 4.7,
  },
]
